/** Colunas para listagem/busca — evita `view_clientes_completo` (5 subqueries por linha → timeout em Catalão). */
export const CLIENTES_LIST_SELECT = [
  'id',
  'codigo',
  'nome',
  'email',
  'telefone_principal',
  'status',
  'tipo_cliente',
  'cliente_vip',
  'bloqueado',
  'empresa_id',
  'created_at',
  'cpf',
  'data_nascimento',
  'rg',
  'sexo',
  'estado_civil',
  'profissao',
  'nome_mae',
  'whatsapp',
  'endereco_cep',
  'endereco_logradouro',
  'endereco_numero',
  'endereco_bairro',
  'endereco_cidade',
  'endereco_estado',
  'usa_endereco_residencial_cobranca',
  'endereco_cob_cep',
  'endereco_cob_logradouro',
  'endereco_cob_numero',
  'endereco_cob_bairro',
  'endereco_cob_cidade',
  'endereco_cob_uf',
  'origem_canal',
].join(',');

export const CLIENTES_LIST_TABLE = 'clientes' as const;
