-- Estado civil: valores da proposta (ex.: separado_judicialmente) excediam VARCHAR(20).
-- A view view_clientes_completo depende da coluna; recria após o ALTER TYPE.
DROP VIEW IF EXISTS public.view_clientes_completo;

ALTER TABLE public.clientes
  ALTER COLUMN estado_civil TYPE varchar(50)
  USING left(coalesce(estado_civil, ''), 50);

COMMENT ON COLUMN public.clientes.estado_civil IS 'Estado civil do titular (códigos curtos ou legado da proposta).';

CREATE VIEW public.view_clientes_completo AS
 SELECT id,
    codigo,
    nome,
    cpf,
    rg,
    data_nascimento,
    sexo,
    estado_civil,
    nacionalidade,
    profissao,
    email,
    telefone_principal,
    telefone_secundario,
    celular,
    aceita_comunicacao,
    endereco_cep,
    endereco_logradouro,
    endereco_numero,
    endereco_complemento,
    endereco_bairro,
    endereco_cidade,
    endereco_estado,
    endereco_pais,
    campos_personalizados,
    ativo,
    vendedor_id,
    criado_por_user_id,
    created_at,
    updated_at,
    deleted_at,
    empresa_id,
    nome_social,
    nome_pai,
    nome_mae,
    naturalidade_cidade,
    naturalidade_uf,
    renda_mensal_faixa,
    escolaridade,
    empresa_trabalho,
    foto_url,
    rg_orgao_emissor,
    rg_uf,
    rg_data_emissao,
    cnh_numero,
    cnh_categoria,
    cnh_validade,
    titulo_eleitor,
    ctps_numero,
    pis_pasep,
    certificado_militar,
    certidao_numero,
    certidao_tipo,
    passaporte,
    email_secundario,
    telefone_celular2,
    telefone_comercial,
    whatsapp,
    whatsapp_preferencial,
    facebook,
    instagram,
    preferencia_contato,
    melhor_horario_contato,
    endereco_com_cep,
    endereco_com_logradouro,
    endereco_com_numero,
    endereco_com_complemento,
    endereco_com_bairro,
    endereco_com_cidade,
    endereco_com_uf,
    cargo_funcao,
    ramal,
    usa_endereco_residencial_cobranca,
    endereco_cob_cep,
    endereco_cob_logradouro,
    endereco_cob_numero,
    endereco_cob_complemento,
    endereco_cob_bairro,
    endereco_cob_cidade,
    endereco_cob_uf,
    endereco_referencia,
    tipo_residencia,
    tempo_residencia_anos,
    tipo_cliente,
    segmento,
    score_credito,
    nivel_relacionamento,
    tags,
    bloqueado,
    motivo_bloqueio,
    cliente_vip,
    origem_canal,
    indicado_por_cliente_id,
    data_primeiro_contato,
    forma_pagamento_preferencial,
    dia_vencimento_preferido,
    limite_credito_centavos,
    desconto_padrao,
    banco_principal,
    agencia,
    conta_corrente,
    tipo_conta,
    pix_chaves,
    aceite_termo_uso,
    aceite_termo_uso_data,
    aceite_termo_uso_ip,
    aceite_politica_privacidade,
    aceite_politica_data,
    consentimento_marketing,
    consentimento_marketing_data,
    consentimento_compartilhamento,
    opt_out_comunicacao,
    opt_out_motivo,
    cliente_desde,
    valor_total_gasto_centavos,
    quantidade_contratos_ativos,
    quantidade_sinistros,
    status,
    calcular_idade(data_nascimento) AS idade,
    formatar_cpf(cpf::text) AS cpf_formatado,
    ( SELECT count(*) AS count
           FROM beneficiarios b
          WHERE b.cliente_id = c.id AND b.ativo = true AND b.deleted_at IS NULL) AS total_beneficiarios,
    ( SELECT count(*) AS count
           FROM assinaturas a
          WHERE a.cliente_id = c.id AND a.status::text = 'ativo'::text) AS total_contratos_ativos,
    ( SELECT count(*) AS count
           FROM contatos_emergencia ce
          WHERE ce.cliente_id = c.id) AS total_contatos_emergencia,
    ( SELECT count(*) AS count
           FROM dados_medicos dm
          WHERE dm.cliente_id = c.id) AS possui_dados_medicos,
    ( SELECT count(*) AS count
           FROM documentos d
          WHERE d.entidade_tipo::text = 'cliente'::text AND d.entidade_id = c.id AND d.status::text = 'ativo'::text) AS total_documentos
   FROM clientes c
  WHERE deleted_at IS NULL;
