-- Bairros da rota do cobrador Bruno Rosa Bernades (Catalão — GO)
UPDATE public.cobradores
SET
  bairros_atuacao = '[
    "AEROPORTO","AYRTON SENNA","BAIRRO DAS AMERICAS","BAIRRO DOS LUCAS","CENTRO",
    "CIDADE JARDIM","CONQUISTA","COPACABANA","CRUZEIRO","CRUZEIRO I","CRUZEIRO II",
    "DAS AMERICAS","DONA MATILDE","DONA SOFIA","ELIAS SAFATLE","EVELINA NOUR",
    "GOIANIENCE","GOIANIENSE","IPANEMA","JARDIM FLORENCA","JARDIM PRIMAVERA",
    "LAGO DAS MANSOES","LEBLON","MAE DE DEUS","MORADA DO SOL","NOVO HORIZONTE",
    "PARATI","PARQUE DOS BURITIS","PARQUE IMPERIAL","PAULISTA","PRIMAVERA","PROGRESSO",
    "RESIDENCIAL PARATI","SANTA CRUZ","SANTA HELENA","SANTA HELENA II","SANTA MONICA",
    "SANTA RITA","SAO FRANCISCO","SAO JOAO","SAO LUCAS","SETOR LEAO","SETOR UNIVERSITARIO",
    "TEOTONIO VILELA","UNIVERSITARIO","VILA CHAUD","VILA CRUZEIRO","VILA MARIA","VILA UNIAO"
  ]'::jsonb,
  updated_at = now()
WHERE nome ILIKE '%bruno%'
  AND (area_atuacao ILIKE '%catalão%' OR area_atuacao ILIKE '%catalao%');
