-- Bairros da rota do cobrador Ederlan Mendes da Silva (Catalão — GO)
UPDATE public.cobradores
SET
  bairros_atuacao = '[
    "ALBINO ALVINO","ALTO DA BOA VISTA","ALTO DA BOA VISTA II","ALVINO ALBINO","BELA VISTA",
    "BOLANGE","BRASILIA","CASTELO BRANCO","CASTELO BRANCO II","CASTELO I","CENTRO","DIMIC",
    "DONA ALMERINDA","ELDORADO","ESTRELA","FLAMBOYANT","ITALIA","JARDIM ACACIAS",
    "JARDIM BRASILIA","JARDIM CATALAO","JARDIM COLONIAL","JARDIM EUROPA","JARDIM PARAISO",
    "JARDIM PAULISTA","JARDIM PLANALTO","JK","LIBERDADE","LIBERDADE I","LIBERDADE II","LINS",
    "MANGUEIRA","MARCONI","MARGON","MARGON 2","MARGON I","MARGON II","MARGON III",
    "MARIA AMELIA 1","MARIA AMELIA 2","MARIA AMELIA II","MONSENHOR SOUZA","MULTIRAO",
    "NOSSA SENHORA DE FATIMA","NOSSA SR DE FATIMA","PAINEIRAS","PARAISO",
    "PARQUE DAS MANGUEIRAS","PIO GOMES","PIRAPITINGA","PONTAL NORTE","POR DO SOL",
    "PORTAL DO LAGO I","PORTAL DO LAGO II","PORTAO DO LAGO 2","RESIDENCIAL DONA ALMERINDA",
    "RESIDENCIAL ELDORADO","RESIDENCIAL GERALDA EVANGELISTA DA ROCHA","RESIDENCIAL LIZ",
    "SANTA TEREZINHA","SANTO ANTONIO","SAO JOSE","TRES CRUZES","VALE DO SOL",
    "VEREDA DOS BURITIS","VILA ERONDINA","VILA LIBERDADE","VILAGE"
  ]'::jsonb,
  updated_at = now()
WHERE nome ILIKE '%ederlan%'
  AND (area_atuacao ILIKE '%catalão%' OR area_atuacao ILIKE '%catalao%');
